const ORDER_CREATE = {
  id: 5993251733802,
  admin_graphql_api_id: "gid://shopify/Order/5993251733802",
  app_id: 580111,
  browser_ip: "190.120.253.206",
  buyer_accepts_marketing: false,
  cancel_reason: null,
  cancelled_at: null,
  cart_token: "Z2NwLXVzLWVhc3QxOjAxSjAxQ0FHQjdKOTI4NjBSQzRBMU5KUE5I",
  checkout_id: 37468630516010,
  checkout_token: "f5f1a040996d8041486af5f6d7b5575e",
  client_details: {
    accept_language: "en-AR",
    browser_height: null,
    browser_ip: "190.120.253.206",
    browser_width: null,
    session_hash: null,
    user_agent:
      "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
  },
  closed_at: null,
  company: null,
  confirmation_number: "C5G0Z8Z9L",
  confirmed: true,
  contact_email: "jose.montano@vnstudios.com",
  created_at: "2024-06-10T11:30:18-04:00",
  currency: "ARS",
  current_subtotal_price: "917.50",
  current_subtotal_price_set: {
    shop_money: { amount: "917.50", currency_code: "ARS" },
    presentment_money: { amount: "917.50", currency_code: "ARS" },
  },
  current_total_additional_fees_set: null,
  current_total_discounts: "857.50",
  current_total_discounts_set: {
    shop_money: { amount: "857.50", currency_code: "ARS" },
    presentment_money: { amount: "857.50", currency_code: "ARS" },
  },
  current_total_duties_set: null,
  current_total_price: "917.50",
  current_total_price_set: {
    shop_money: { amount: "917.50", currency_code: "ARS" },
    presentment_money: { amount: "917.50", currency_code: "ARS" },
  },
  current_total_tax: "0.00",
  current_total_tax_set: {
    shop_money: { amount: "0.00", currency_code: "ARS" },
    presentment_money: { amount: "0.00", currency_code: "ARS" },
  },
  customer_locale: "en-AR",
  device_id: null,
  discount_codes: [],
  email: "jose.montano@vnstudios.com",
  estimated_taxes: false,
  financial_status: "paid",
  fulfillment_status: null,
  landing_site: "/",
  landing_site_ref: null,
  location_id: null,
  merchant_of_record_app_id: null,
  name: "#1015",
  note: null,
  note_attributes: [],
  number: 15,
  order_number: 1015,
  order_status_url:
    "https://j-montano-dev.myshopify.com/82524078378/orders/f15e5b294fa1a837c68d933efb37b15b/authenticate?key=51513c10db99efb8b1305d8520346f21&none=VQVTClJBXFtaQ1xI",
  original_total_additional_fees_set: null,
  original_total_duties_set: null,
  payment_gateway_names: ["bogus"],
  phone: null,
  po_number: null,
  presentment_currency: "ARS",
  processed_at: "2024-06-10T11:30:17-04:00",
  reference: "8792c295fcb9e8f56542a6b5b1d2d030",
  referring_site: "",
  source_identifier: "8792c295fcb9e8f56542a6b5b1d2d030",
  source_name: "web",
  source_url: null,
  subtotal_price: "917.50",
  subtotal_price_set: {
    shop_money: { amount: "917.50", currency_code: "ARS" },
    presentment_money: { amount: "917.50", currency_code: "ARS" },
  },
  tags: "",
  tax_exempt: false,
  tax_lines: [],
  taxes_included: false,
  test: true,
  token: "f15e5b294fa1a837c68d933efb37b15b",
  total_discounts: "857.50",
  total_discounts_set: {
    shop_money: { amount: "857.50", currency_code: "ARS" },
    presentment_money: { amount: "857.50", currency_code: "ARS" },
  },
  total_line_items_price: "1775.00",
  total_line_items_price_set: {
    shop_money: { amount: "1775.00", currency_code: "ARS" },
    presentment_money: { amount: "1775.00", currency_code: "ARS" },
  },
  total_outstanding: "0.00",
  total_price: "917.50",
  total_price_set: {
    shop_money: { amount: "917.50", currency_code: "ARS" },
    presentment_money: { amount: "917.50", currency_code: "ARS" },
  },
  total_shipping_price_set: {
    shop_money: { amount: "0.00", currency_code: "ARS" },
    presentment_money: { amount: "0.00", currency_code: "ARS" },
  },
  total_tax: "0.00",
  total_tax_set: {
    shop_money: { amount: "0.00", currency_code: "ARS" },
    presentment_money: { amount: "0.00", currency_code: "ARS" },
  },
  total_tip_received: "0.00",
  total_weight: 100,
  updated_at: "2024-06-10T11:30:20-04:00",
  user_id: null,
  billing_address: {
    first_name: "Jose",
    address1: "Bello Monte",
    phone: null,
    city: "Caracas",
    zip: "1050",
    province: "Ciudad Autónoma de Buenos Aires",
    country: "Argentina",
    last_name: "Montaño",
    address2: "Apto B32",
    company: null,
    latitude: null,
    longitude: null,
    name: "Jose Montaño",
    country_code: "AR",
    province_code: "C",
  },
  customer: {
    id: 7323708096810,
    email: "jose.montano@vnstudios.com",
    created_at: "2023-09-11T11:14:13-04:00",
    updated_at: "2024-06-10T11:30:19-04:00",
    first_name: "Jose",
    last_name: "Montaño",
    state: "enabled",
    note: "",
    verified_email: true,
    multipass_identifier: null,
    tax_exempt: false,
    phone: null,
    email_marketing_consent: {
      state: "not_subscribed",
      opt_in_level: "single_opt_in",
      consent_updated_at: null,
    },
    sms_marketing_consent: null,
    tags: "conditional, customer-test",
    currency: "ARS",
    tax_exemptions: [],
    admin_graphql_api_id: "gid://shopify/Customer/7323708096810",
    default_address: {
      id: 9500600140074,
      customer_id: 7323708096810,
      first_name: "Jose",
      last_name: "Montaño",
      company: "",
      address1: "Bello Monte",
      address2: "Apto B32",
      city: "Caracas",
      province: "Ciudad Autónoma de Buenos Aires",
      country: "Argentina",
      zip: "1050",
      phone: null,
      name: "Jose Montaño",
      province_code: "C",
      country_code: "AR",
      country_name: "Argentina",
      default: true,
    },
  },
  discount_applications: [
    {
      target_type: "line_item",
      type: "automatic",
      value: "50.0",
      value_type: "percentage",
      allocation_method: "across",
      target_selection: "entitled",
      title: "Conditional Discount 50% OFF",
    },
    {
      target_type: "line_item",
      type: "automatic",
      value: "10.0",
      value_type: "percentage",
      allocation_method: "across",
      target_selection: "entitled",
      title: "10% Flash ",
    },
  ],
  fulfillments: [],
  line_items: [
    {
      id: 15104420741418,
      admin_graphql_api_id: "gid://shopify/LineItem/15104420741418",
      attributed_staffs: [],
      current_quantity: 1,
      fulfillable_quantity: 1,
      fulfillment_service: "manual",
      fulfillment_status: null,
      gift_card: false,
      grams: 100,
      name: "(CUSTOM) IN THEIR FOOTSTEPS NAIDOC WEEK 2023 UPF50+ BAMBOO (SIMPSON) POLO SHIRT",
      price: "75.00",
      price_set: [
        {
          shop_money: { amount: "75.00", currency_code: "ARS" },
          presentment_money: { amount: "75.00", currency_code: "ARS" },
        },
      ],
      product_exists: true,
      product_id: 8891177828650,
      properties: [],
      quantity: 1,
      requires_shipping: true,
      sku: "test-001",
      taxable: false,
      title:
        "(CUSTOM) IN THEIR FOOTSTEPS NAIDOC WEEK 2023 UPF50+ BAMBOO (SIMPSON) POLO SHIRT",
      total_discount: "0.00",
      total_discount_set: [
        {
          shop_money: { amount: "0.00", currency_code: "ARS" },
          presentment_money: { amount: "0.00", currency_code: "ARS" },
        },
      ],
      variant_id: 47528186970410,
      variant_inventory_management: "shopify",
      variant_title: null,
      vendor: "j-montano-dev",
      tax_lines: [Array],
      duties: [],
      discount_allocations: [
        {
          amount: "7.50",
          amount_set: {
            shop_money: { amount: "7.50", currency_code: "ARS" },
            presentment_money: { amount: "7.50", currency_code: "ARS" },
          },
          discount_application_index: 1,
        },
      ],
    },
    {
      id: 15104420774186,
      admin_graphql_api_id: "gid://shopify/LineItem/15104420774186",
      attributed_staffs: [],
      current_quantity: 2,
      fulfillable_quantity: 2,
      fulfillment_service: "manual",
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: "(CUSTOM) IN THEIR FOOTSTEPS NAIDOC WEEK 2023 UPF50+ BAMBOO (SIMPSON) CUP",
      price: "850.00",
      price_set: [
        {
          shop_money: { amount: "850.00", currency_code: "ARS" },
          presentment_money: { amount: "850.00", currency_code: "ARS" },
        },
      ],
      product_exists: true,
      product_id: 8891399242026,
      properties: [],
      quantity: 2,
      requires_shipping: true,
      sku: "696969",
      taxable: false,
      title:
        "(CUSTOM) IN THEIR FOOTSTEPS NAIDOC WEEK 2023 UPF50+ BAMBOO (SIMPSON) CUP",
      total_discount: "0.00",
      total_discount_set: [
        {
          shop_money: { amount: "0.00", currency_code: "ARS" },
          presentment_money: { amount: "0.00", currency_code: "ARS" },
        },
      ],
      variant_id: 47528930279722,
      variant_inventory_management: "shopify",
      variant_title: null,
      vendor: "j-montano-dev",
      tax_lines: [Array],
      duties: [],
      discount_allocations: [
        {
          amount: "850.00",
          amount_set: {
            shop_money: { amount: "850.00", currency_code: "ARS" },
            presentment_money: { amount: "850.00", currency_code: "ARS" },
          },
          discount_application_index: 0,
        },
      ],
    },
  ],
  payment_terms: null,
  refunds: [],
  shipping_address: {
    first_name: "Jose",
    address1: "Bello Monte",
    phone: null,
    city: "Caracas",
    zip: "1050",
    province: "Ciudad Autónoma de Buenos Aires",
    country: "Argentina",
    last_name: "Montaño",
    address2: "Apto B32",
    company: null,
    latitude: 10.490076,
    longitude: -66.87365319999999,
    name: "Jose Montaño",
    country_code: "AR",
    province_code: "C",
  },
  shipping_lines: [
    {
      id: 4883904725290,
      carrier_identifier: "650f1a14fa979ec5c74d063e968411d4",
      code: "Standard",
      discounted_price: "0.00",
      discounted_price_set: [Object],
      is_removed: false,
      phone: null,
      price: "0.00",
      price_set: [Object],
      requested_fulfillment_service_id: null,
      source: "shopify",
      title: "Standard",
      tax_lines: [],
      discount_allocations: [],
    },
  ],
};
